FROM python:3.7.5

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_ENV dev

RUN apt-get update
RUN apt-get -y install gcc g++ cmake python-dev python3-dev

COPY . /app/
WORKDIR /app/

COPY ./requirements.txt /app/requirements.txt
COPY ./db.sqlite3 /app/db.sqlite3

RUN pip3 install --upgrade pip
RUN pip3 install -r /app/requirements.txt

RUN python3 /app/manage.py makemigrations
RUN python3 /app/manage.py migrate

USER root